[template]
src = "wp-nginx.tmpl"
dest = "/etc/nginx/conf.d/wp.conf"
keys = [ "/upstream" ]
owner = "root"
mode = "0644"
check_cmd = "/usr/sbin/nginx -t"
reload_cmd = "kill -HUP $(cat /run/nginx.pid )"
